### ISSUE TITLE
Your queue position is: -1 (PASS)

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#9] opened 2016-12-04 05:54 UTC
![untitled6](https://cloud.githubusercontent.com/assets/13591955/20864362/2eb0d1e6-b9bc-11e6-9522-76af95b5ebc5.png)

**Comment by mateodelnorte** [comment] 2016-12-05 01:47
What steps did you take to create this scenario? 

I'm not able to reproduce. 

Scenarios attempted: 
```
1. accept all participants
2. join as new participant
3. new participant is given queue position 1
```
```
1. accept all participants
2. unaccept participant
3. participant is re-assigned position 1
```

**Comment by MHEBE3ET** [comment] 2016-12-05 15:09
I will reproduce and provide steps. I've seen this many times.

**Comment by MHEBE3ET** [comment] 2016-12-05 15:24
As I was accepting participants queue position became negative. See below

![untitled2](https://cloud.githubusercontent.com/assets/13591955/20890453/f55ef976-bad4-11e6-90e2-e1cdad9fbc15.png)

**Comment by mateodelnorte** [comment] 2016-12-05 16:33
Closing this one as a duplicate of #3. Will fix there.

**Closed as completed by mateodelnorte** 2016-12-05 16:33 UTC

**Comment by MHEBE3ET** [comment] 2016-12-10 04:05
pass
